[package]
name = "pgfplots"
version = "0.5.1" # Remember to also change this in the README.md
edition = "2021"
license = "MIT"
description = "A Rust library to generate publication-quality figures"
readme = "README.md"
repository = "https://github.com/DJDuque/pgfplots"
keywords = ["pgfplots", "plotting", "plot", "visualization", "latex"]
categories = ["visualization"]
documentation = "https://docs.rs/pgfplots"
exclude = ["examples/*.png"]

[dependencies]
tectonic = { version = "0.12", optional = true }
opener = "0.7.2"
rand = "0.9.0"
tempfile = "3"
thiserror = "2.0.12"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
